export const LOAD_PRODUCTS_FULFILLED = "LOAD_PRODUCTS_FULFILLED";
export const LOAD_PRODUCTS_REJECTED = "LOAD_PRODUCTS_REJECTED";
export const LOAD_PRODUCTS_PENDING = "LOAD_PRODUCTS_PENDING";
export const GET_PRODUCT_BY_ID = "GET_PRODUCT_BY_ID";
