export const LOAD_REVIEWS_FULFILLED = "LOAD_REVIEWS_FULFILLED";
export const LOAD_REVIEWS_REJECTED = "LOAD_REVIEWS_REJECTED";
export const LOAD_REVIEWS_PENDING = "LOAD_REVIEWS_PENDING";
export const POST_AND_GET_REVIEW_REJECTED = "POST_AND_GET_REVIEW_REJECTED";
